---
title: "Nebraska"
author: "Helen Miller"
output:
  html_document: default
  html_notebook: default
---

```{r, cache = TRUE}
source("~/Projects/NBI/R/convert2016.R")
nbi <- convert2016("~/Data/2016hwybronlyonefile.zip")
ne <- subset(nbi, stateCode == "NE")
```
```{r, cache = TRUE}
library(MazamaSpatialUtils)
setSpatialDataDir("~/Data/Spatial")
MazamaSpatialUtils::convertUSCensusCounties()
loadSpatialData("USCensusCounties")
```
```{r}
library(maps)
library(MazamaSpatialUtils)
neCounties <- subset(USCensusCounties, stateCode == "NE")
ne$county <- getUSCounty(ne$longitude, ne$latitude, dataset = "USCensusCounties", stateCode = "NE")
```

#Overall Distribution of Bridges

```{r}
library(maps)
map("state", "neb")
with(dplyr::filter(nbi, water == 1 & stateCode == "NE"), points(longitude, latitude, pch = 2, cex = .2))
with(dplyr::filter(nbi, water == 0 & stateCode == "NE"), points(longitude, latitude, pch = 2, cex = .5, col = "red"))
```

#Bridge Age 

```{r}
hist(ne$yearBuilt)
```

```{r}
breaks <- c(0,seq(16,136, by = 20))
neColors <- RColorBrewer::brewer.pal(7, "PuRd")
colorIndex <- .bincode(ne$age, breaks = breaks)
ne$colorIndex <- colorIndex
map("state", "neb")
points(ne$longitude, ne$latitude, cex = .3, pch = 17, col = neColors[colorIndex])
legend("bottomleft", c("1880-1900", "1900-1920", "1920-1940", "1940-1960", "1960-1980", "1980-2000", "2000-2017"), pch = 17, col = neColors[7:1])
```

```{r}
map("state", "neb")
with(subset(ne, water == 0), points( longitude, latitude, cex = .5, pch = 17, col = neColors[colorIndex]))
```

#Aggregated by county: 

```{r}
meanAgeByCounty <- aggregate(data=ne, age~county, FUN = mean)
breaks <- c(24.4, seq(30,55, by = 5), 60.2)
colorIndex <- .bincode(meanAgeByCounty$age, breaks = breaks)
names(colorIndex) <- meanAgeByCounty$county
plot(neCounties, col = neColors[colorIndex[neCounties$countyName]])
legend("bottomleft", c("25-30", "30-35", "35-40", "40-45", "45-50","50-55", "55-60"), pch = 15, col = neColors)

getmode <- function(v) {
uniqv <- unique(v)
uniqv[which.max(tabulate(match(v, uniqv)))]
}

modeYearByCounty <- aggregate(data = ne, yearBuilt~county, FUN = getmode)
hist(modeYearByCounty$yearBuilt)
breaks <- c(seq(1929, 1999, by = 10), 2017)
modeIndex <- .bincode(modeYearByCounty$yearBuilt, breaks = breaks)
modeColors <- RColorBrewer::brewer.pal(8, "PuRd")
names(modeIndex) <- modeYearByCounty$county
plot(neCounties, col = modeColors[8:1][modeIndex[neCounties$countyName]])
legend("bottomleft", c("1930s", "1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s"), pch = 15, col = modeColors)
```

#Traffic
```{r}
map("state", "neb")
points(ne$longitude, ne$latitude, pch = 2, cex = ne$averageCarCount/20000)
```








